### ISSUE TITLE
Compilation error with rustc 1.56.1 run release on main branch

### ISSUE THREAD

**Issue by Froidoh** [udoprog/OxidizeBot#111]
Hey there!

Not sure if anyone is interested, this looks a bit... stale, not to say abandoned.

`rustc 1.56.1 (59eed8a2a 2021-11-01)`

`cargo run --release`

> error[E0308]: mismatched types
    --> /home/froidoh/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/math.rs:1253:19
     |
1253 |     let rem = n % bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot mod `usize` by `u32`
    --> /home/froidoh/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/math.rs:1253:17
     |
1253 |     let rem = n % bits;
     |                 ^ no implementation for `usize % u32`
     |
     = help: the trait `Rem<u32>` is not implemented for `usize`

error[E0308]: mismatched types
    --> /home/froidoh/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/math.rs:1254:19
     |
1254 |     let div = n / bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot divide `usize` by `u32`
    --> /home/froidoh/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/math.rs:1254:17
     |
1254 |     let div = n / bits;
     |                 ^ no implementation for `usize / u32`
     |
     = help: the trait `Div<u32>` is not implemented for `usize`

   Compiling dirs-next v2.0.0
   Compiling mime_guess v2.0.3
   Compiling rand_core v0.6.1
   Compiling rand_core v0.5.1
   Compiling http-body v0.4.0
   Compiling headers-core v0.2.0
   Compiling inotify v0.9.2
Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `lexical-core` due to 27 previous errors

**same error with `cargo rr +nightly`**

**Comment by pavelpilar** [comment]
Thank you for the notice. Feel free to use the branch from my PR or simply run `cargo update -p lexical-core` on your end while we get this ironed out.

You're right that there's no development going on right now, but the bot should be in a usable state and I'm always happy to look at any bug reports when I have the time.
