### ISSUE TITLE
Error: Failed to build pub/sub client

### ISSUE THREAD

**Issue by chilledsheep** [udoprog/OxidizeBot#167]
i try to run 1.2.1-beta.1 on MacOS and i get these errors over and over again:

Failed to build pup/sub client
caused by: URL error: TLS support not compiled in
caused by: TLS support not compiled in
Attempting to reconnect

**Comment by udoprog** [comment]
Thanks for the report. This should be easy to fix since it's probably just a dependency configuration missing.

**Comment by chilledsheep** [comment]
tried 1.2.0 on MacOS and the same error happens

**Comment by udoprog** [comment]
I'm shipping `1.2.1-beta.2` which should have the TLS feature enabled, please give it a try once it's available!
