### ISSUE TITLE
Build Fails with tokio revspec not found

### ISSUE THREAD

**Issue by PSeitz** [udoprog/OxidizeBot#68]
Updating git repository `https://github.com/udoprog/tokio`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `tokio`

Caused by:
  Unable to update https://github.com/udoprog/tokio?branch=rwlock-map#b4d2d250

Caused by:
  revspec 'b4d2d250db724e929c51d36fce892322d6fa10c0' not found; class=Reference (4); code=NotFound (-3)

**Comment by udoprog** [comment]
Thanks for the report!

Seems like the lock file might be outdated. I'm waiting for a patch to be merged in Tokio which provides the lock guards (tokio-rs/tokio#2445), and I recently updated this branch.

Running `cargo update` to update it to the latest revspec should fix it. I'll add a commit which does this ASAP.
