### ISSUE TITLE
oxidize: Some scope errors send two responses

### ISSUE THREAD

**Issue by pavelpilar** [udoprog/OxidizeBot#89]
`User: !song promote 5`
`OxidizeBot: Do you think this is a democracy User? LUL`
`OxidizeBot: User -> Sorry, something went wrong :(`

**Comment by udoprog** [comment]
Hey, any chance you can have a peek in the error log? It should say what went wrong.

**Comment by pavelpilar** [comment]
This is the error:
```
ERROR oxidize::irc - Error when processing command
ERROR oxidize::irc - caused by: Scope `song/edit-queue` not associated with user Some("User")
```
After some testing I found out the issue also affects other commands, `!command edit` gives the proper response but `!auth permit` or `!game edit` also send the error.
